baseURL = "https://spatium-novum.com/"
title = "Spatium Novum"
languageCode = "en-us"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"] # Enable JSON output for the homepage

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/thoughts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
